# modelo de secret

apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-otlp          
  namespace: solier-local          
type: Opaque
stringData:                          
  GRAFANA_CLOUD_OTLP_ENDPOINT: "https://otlp-gateway-prod-sa-east-1.grafana.net/otlp"
  GRAFANA_CLOUD_OTLP_AUTH: "TOKENDEACESSOBASE64QUEOGRAFANADISPONIBILIZAA67"
