name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Render the overlays
        run: |
          kubectl kustomize k8s > /dev/null
          kubectl kustomize overlays/dev > /dev/null
          kubectl kustomize overlays/prod > /dev/null
